-- MySQL Script generated by MySQL Workbench
-- Fri Jun 30 19:11:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema patient
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema patient
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `patient` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `patient` ;

-- -----------------------------------------------------
-- Table `patient`.`dimension_drug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patient`.`dimension_drug` (
  `drug_ndc` INT NOT NULL,
  `drug_name` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`drug_ndc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `patient`.`dimension_drugadministration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patient`.`dimension_drugadministration` (
  `drug_form_code` VARCHAR(100) NOT NULL,
  `drug_form_desc` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`drug_form_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `patient`.`dimension_drugbrandgeneric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patient`.`dimension_drugbrandgeneric` (
  `drug_brand_generic_code` INT NOT NULL,
  `drug_brand_generic_desc` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`drug_brand_generic_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `patient`.`dimension_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patient`.`dimension_member` (
  `member_id` INT NOT NULL,
  `member_first_name` TEXT NULL DEFAULT NULL,
  `member_last_name` TEXT NULL DEFAULT NULL,
  `member_birth_date` TEXT NULL DEFAULT NULL,
  `member_age` INT NULL DEFAULT NULL,
  `member_gender` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`member_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `patient`.`fact_patientsprescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patient`.`fact_patientsprescription` (
  `member_id` INT NOT NULL,
  `drug_ndc` INT NOT NULL,
  `drug_form_code` VARCHAR(100) NOT NULL,
  `drug_brand_generic_code` INT NOT NULL,
  `fill_date` TEXT NOT NULL,
  `copay` INT NULL DEFAULT NULL,
  `insurancepaid` INT NULL DEFAULT NULL,
  INDEX `FK_member` (`member_id` ASC) VISIBLE,
  INDEX `FK_drug` (`drug_ndc` ASC) VISIBLE,
  INDEX `FK_drugbrandgeneric` (`drug_brand_generic_code` ASC) VISIBLE,
  INDEX `FK_drugadministration` (`drug_form_code` ASC) VISIBLE,
  PRIMARY KEY (`member_id`, `drug_ndc`, `fill_date`, `drug_brand_generic_code`, `drug_form_code`),
  CONSTRAINT `FK_drug`
    FOREIGN KEY (`drug_ndc`)
    REFERENCES `patient`.`dimension_drug` (`drug_ndc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_drugadministration`
    FOREIGN KEY (`drug_form_code`)
    REFERENCES `patient`.`dimension_drugadministration` (`drug_form_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_drugbrandgeneric`
    FOREIGN KEY (`drug_brand_generic_code`)
    REFERENCES `patient`.`dimension_drugbrandgeneric` (`drug_brand_generic_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_member`
    FOREIGN KEY (`member_id`)
    REFERENCES `patient`.`dimension_member` (`member_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
